In [1]:
import pandas as pd

In [2]:
pd.read_json('train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [3]:
pd.read_json('https://microsoftedge.github.io/Demos/json-dummy-data/64KB.json')

,name,language,id,bio,version
0,Adeel Solangi,Sindhi,V59OF92YF627HFY0,Donec lobortis eleifend condimentum. Cras dict...,6.10
1,Afzal Ghaffar,Sindhi,ENTOCR13RSCLZ6KU,"Aliquam sollicitudin ante ligula, eget malesua...",1.88
2,Aamir Solangi,Sindhi,IAKPO3R4761JDRVG,Vestibulum pharetra libero et velit gravida eu...,7.27
3,Abla Dilmurat,Uyghur,5ZVOEPMJUI4MB4EN,Donec lobortis eleifend condimentum. Morbi ac ...,2.53
4,Adil Eli,Uyghur,6VTI8X6LL0MMPJCC,"Vivamus id faucibus velit, id posuere leo. Mor...",6.49
...,...,...,...,...,...
192,Kristín Sigurðardóttir,Icelandic,ZP5TBBYX6RI2UJ31,Cras dictum dolor lacinia lectus vehicula rutr...,2.80
193,Rohini Vasav,Hindi,UEFML43TCGS04KWM,"Ut accumsan, est vel fringilla varius, purus a...",9.30
194,Sunil Kapoor,Hindi,VY2A0APGVHK5NAW2,"Proin tempus eu risus nec mattis. Ut dictum, l...",8.04
195,Zamokuhle Zulu,isiZulu,XU7BX2F8M5PVZ1EF,Etiam congue dignissim volutpat. Phasellus tin...,8.39
196,Bhupesh Menon,Hindi,0CEPNRDV98KT3ORP,Maecenas tempus neque ut porttitor malesuada. ...,2.69

In [4]:
#Now SQL Data
!pip install mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     --- ------------------------------------ 1.0/11.9 MB 6.3 MB/s eta 0:00:02
     ------ --------------------------------- 1.8/11.9 MB 4.8 MB/s eta 0:00:03
     -------- ------------------------------- 2.6/11.9 MB 4.5 MB/s eta 0:00:03
     ----------- ---------------------------- 3.4/11.9 MB 4.3 MB/s eta 0:00:02
     --------------- ------------------------ 4.5/11.9 MB 4.2 MB/s eta 0:00:02
     ----------------- ---------------------- 5.2/11.9 MB 4.1 MB/s eta 0:00:02
     -------------------- ------------------- 6.0/11.9 MB 4.1 MB/s eta 0:00:02
     ----------------------- ---------------- 6.8/11.9 MB 4.1 MB/s eta 0:00:02
     ------------------------- -------------- 7.6/11.9 MB 4.1 MB/s eta 0:00:02
     ----------------------------- ---------- 8.7/11.9 MB 4.0 MB/s eta 0:00:01
     ------------------------------- -------- 9.4/11.9 MB 4.0 MB/s eta 0:00:01
     ---------------------------------- ----- 10.2/11.9 MB 4.0 MB/s eta 0:00:01
     ------------------------------------- -- 11.0/11.9 MB 4.0 MB/s eta 0:00:01
     ---------------------------------------  11.8/11.9 MB 4.0 MB/s eta 0:00:01
     ---------------------------------------- 11.9/11.9 MB 3.9 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (setup.py): started
  Building wheel for mysql.connector (setup.py): finished with status 'done'
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp313-cp313-win_amd64.whl size=247959 sha256=cd7358ce2a01331171bafc8f5cc973e2b16b702f52e9a56d6be77f73bbefba8a
  Stored in directory: c:\users\sanjog bhalla\appdata\local\pip\cache\wheels\4e\c1\23\9423c444a75266a05275c80ebf5c6efe2368388e976b690a0f
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9

  DEPRECATION: Building 'mysql.connector' using the legacy setup.py bdist_wheel mechanism, which will be removed in a future version. pip 25.3 will enforce this behaviour change. A possible replacement is to use the standardized build interface by setting the `--use-pep517` option, (possibly combined with `--no-build-isolation`), or adding a `pyproject.toml` file to the source tree of 'mysql.connector'. Discussion can be found at https://github.com/pypa/pip/issues/6334

In [6]:
import mysql.connector
mydb = mysql.connector.connect(host='localhost',user='root',password='',database='world')

In [17]:
pd.read_sql_query("SELECT * FROM city WHERE CountryCode = 'USA'",con=mydb)

C:\Users\Sanjog Bhalla\AppData\Local\Temp\ipykernel_31328\1352037546.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM city WHERE CountryCode = 'USA'",con=mydb)

       ID          Name CountryCode        District  Population
0    3793      New York         USA        New York     8008278
1    3794   Los Angeles         USA      California     3694820
2    3795       Chicago         USA        Illinois     2896016
3    3796       Houston         USA           Texas     1953631
4    3797  Philadelphia         USA    Pennsylvania     1517550
..    ...           ...         ...             ...         ...
269  4062       Kenosha         USA       Wisconsin       89447
270  4063         Elgin         USA        Illinois       89408
271  4064        Odessa         USA           Texas       89293
272  4065        Carson         USA      California       89089
273  4066    Charleston         USA  South Carolina       89063

[274 rows x 5 columns]

In [8]:
conda install -c conda-forge sqlalchemy mysql-connector-python

Note: you may need to restart the kernel to use updated packages.

'C:\Users\Sanjog' is not recognized as an internal or external command,
operable program or batch file.

In [9]:
!pip install sqlalchemy mysql-connector-python

Requirement already satisfied: sqlalchemy in c:\users\sanjog bhalla\anaconda3\lib\site-packages (2.0.39)
Collecting mysql-connector-python
  Downloading mysql_connector_python-9.5.0-cp313-cp313-win_amd64.whl.metadata (7.7 kB)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\sanjog bhalla\anaconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\sanjog bhalla\anaconda3\lib\site-packages (from sqlalchemy) (4.12.2)
Downloading mysql_connector_python-9.5.0-cp313-cp313-win_amd64.whl (16.5 MB)
   ---------------------------------------- 0.0/16.5 MB ? eta -:--:--
   -- ------------------------------------- 1.0/16.5 MB 6.5 MB/s eta 0:00:03
   ---- ----------------------------------- 1.8/16.5 MB 4.9 MB/s eta 0:00:03
   ------ --------------------------------- 2.6/16.5 MB 4.3 MB/s eta 0:00:04
   -------- ------------------------------- 3.4/16.5 MB 4.3 MB/s eta 0:00:04
   ---------- ----------------------------- 4.2/16.5 MB 4.2 MB/s eta 0:00:03
   ------------ --------------------------- 5.0/16.5 MB 4.1 MB/s eta 0:00:03
   ------------- -------------------------- 5.8/16.5 MB 4.0 MB/s eta 0:00:03
   ---------------- ----------------------- 6.8/16.5 MB 4.0 MB/s eta 0:00:03
   ------------------ --------------------- 7.6/16.5 MB 4.0 MB/s eta 0:00:03
   -------------------- ------------------- 8.4/16.5 MB 4.0 MB/s eta 0:00:03
   ---------------------- ----------------- 9.2/16.5 MB 4.0 MB/s eta 0:00:02
   ------------------------ --------------- 10.0/16.5 MB 4.0 MB/s eta 0:00:02
   -------------------------- ------------- 10.7/16.5 MB 4.0 MB/s eta 0:00:02
   --------------------------- ------------ 11.5/16.5 MB 4.0 MB/s eta 0:00:02
   ------------------------------ --------- 12.6/16.5 MB 4.0 MB/s eta 0:00:01
   -------------------------------- ------- 13.4/16.5 MB 3.9 MB/s eta 0:00:01
   ---------------------------------- ----- 14.2/16.5 MB 3.9 MB/s eta 0:00:01
   ------------------------------------ --- 14.9/16.5 MB 3.9 MB/s eta 0:00:01
   -------------------------------------- - 15.7/16.5 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------  16.3/16.5 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------- 16.5/16.5 MB 3.9 MB/s eta 0:00:00
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.5.0

In [13]:
import sqlalchemy

engine = sqlalchemy.create_engine("mysql+mysqlconnector://root:@localhost/world")

df_city = pd.read_sql_query("SELECT * FROM city", con=engine)
print(df_city)

        ID            Name CountryCode       District  Population
0        1           Kabul         AFG          Kabol     1780000
1        2        Qandahar         AFG       Qandahar      237500
2        3           Herat         AFG          Herat      186800
3        4  Mazar-e-Sharif         AFG          Balkh      127800
4        5       Amsterdam         NLD  Noord-Holland      731200
...    ...             ...         ...            ...         ...
4074  4075      Khan Yunis         PSE     Khan Yunis      123175
4075  4076          Hebron         PSE         Hebron      119401
4076  4077        Jabaliya         PSE     North Gaza      113901
4077  4078          Nablus         PSE         Nablus      100231
4078  4079           Rafah         PSE          Rafah       92020

[4079 rows x 5 columns]

In [18]:
df_city = pd.read_sql_query("SELECT * FROM city WHERE CountryCode LIKE 'USA'", con=engine)
print(df_city)

       ID          Name CountryCode        District  Population
0    3793      New York         USA        New York     8008278
1    3794   Los Angeles         USA      California     3694820
2    3795       Chicago         USA        Illinois     2896016
3    3796       Houston         USA           Texas     1953631
4    3797  Philadelphia         USA    Pennsylvania     1517550
..    ...           ...         ...             ...         ...
269  4062       Kenosha         USA       Wisconsin       89447
270  4063         Elgin         USA        Illinois       89408
271  4064        Odessa         USA           Texas       89293
272  4065        Carson         USA      California       89089
273  4066    Charleston         USA  South Carolina       89063

[274 rows x 5 columns]