In [2]:
import numpy as np 
import pandas as pd

In [3]:
orders = pd.read_csv('orders.csv')
messages = pd.read_csv('messages.csv')

In [4]:
orders.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [5]:
messages.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [6]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [ ]:
messages.info() #the date and time is of type object

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

Working with Dates

In [8]:
#Converting to datetime datatype
orders['date'] = pd.to_datetime(orders['date'])

In [9]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

1. Extract year

In [11]:
orders['date_year'] = orders['date'].dt.year

orders.sample(5)

          date  product_id  city_id  orders  date_year
580 2018-09-29        5965       13       2       2018
315 2018-11-10        3345       13      23       2018
533 2019-01-22        6291       27       1       2019
757 2019-11-11        5848       13       4       2019
936 2019-08-02        2051       13       1       2019

2. Extract Month

In [13]:
orders['date_month_no'] = orders['date'].dt.month

orders.head()

        date  product_id  city_id  orders  date_year  date_month_no
0 2019-12-10        5628       25       3       2019             12
1 2018-08-15        3646       14     157       2018              8
2 2018-10-23        1859       25       1       2018             10
3 2019-08-17        7292       25       1       2019              8
4 2019-01-06        4344       25       3       2019              1

In [15]:
orders['date_month_name'] = orders['date'].dt.month_name()

orders.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

Extract Days

In [17]:
orders['date_day'] = orders['date'].dt.day

orders.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

In [20]:
#Day of week
orders['date_dow'] = orders['date'].dt.dayofweek
orders.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [21]:
#day of week - name

orders['date_dow_name'] = orders['date'].dt.day_name()
orders.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday

In [22]:
# is weekend?

orders['date_is_weekend'] = np.where(orders['date_dow_name'].isin(['Sunday','Saturday']), 1,0)

orders.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1

Extract week of the year

In [25]:
orders['date_week'] = orders['date'].dt.isocalendar().week

orders.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1

Extract Quarter

In [26]:
orders['quarter'] = orders['date'].dt.quarter

orders.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50,4
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33,3
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43,4
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33,3
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1,1

Extract Semester

In [27]:
orders['semester'] = np.where(orders['quarter'].isin([1,2]), 1, 2)

orders.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33,3,2
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1,1,1

Extract Time elapsed between dates

In [28]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2025, 11, 22, 18, 9, 35, 139763)

In [29]:
today - orders['date']

0     2174 days 18:09:35.139763
1     2656 days 18:09:35.139763
2     2587 days 18:09:35.139763
3     2289 days 18:09:35.139763
4     2512 days 18:09:35.139763
                 ...
995   2602 days 18:09:35.139763
996   2543 days 18:09:35.139763
997   2391 days 18:09:35.139763
998   2456 days 18:09:35.139763
999   2230 days 18:09:35.139763
Name: date, Length: 1000, dtype: timedelta64[ns]

In [30]:
(today - orders['date']).dt.days

0      2174
1      2656
2      2587
3      2289
4      2512
       ...
995    2602
996    2543
997    2391
998    2456
999    2230
Name: date, Length: 1000, dtype: int64

In [45]:
# Months passed

np.round((today - orders['date']) / np.timedelta64(1, 'W'),0) #need to do it for months

0      311.0
1      380.0
2      370.0
3      327.0
4      359.0
       ...
995    372.0
996    363.0
997    342.0
998    351.0
999    319.0
Name: date, Length: 1000, dtype: float64

In [46]:
messages.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [47]:
#Converting to datetime datatype

messages['date'] = pd.to_datetime(messages['date'])

In [48]:
messages.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [50]:
messages['hour'] = messages['date'].dt.hour
messages['min'] = messages['date'].dt.minute
messages['sec'] = messages['date'].dt.second

messages.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

Extract Time Part

In [51]:
messages['time'] = messages['date'].dt.time

messages.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

Time difference

In [54]:
today - messages['date']

0     4360 days 17:19:35.139763
1     4224 days 18:29:35.139763
2     4710 days 17:48:35.139763
3     4012 days 17:38:35.139763
4     4409 days 18:58:35.139763
                 ...
995   4999 days 17:19:35.139763
996   4320 days 18:55:35.139763
997   4785 days 18:32:35.139763
998   4901 days 18:35:35.139763
999   4173 days 18:44:35.139763
Name: date, Length: 1000, dtype: timedelta64[ns]

In [56]:
# in seconds

(today - messages['date'])/np.timedelta64(1,'s')

0      3.767664e+08
1      3.650202e+08
2      4.070081e+08
3      3.467003e+08
4      3.810059e+08
           ...
995    4.319760e+08
996    3.733161e+08
997    4.134908e+08
998    4.235133e+08
999    3.606147e+08
Name: date, Length: 1000, dtype: float64

In [57]:
# in minutes

(today - messages['date'])/np.timedelta64(1,'m')

0      6.279440e+06
1      6.083670e+06
2      6.783469e+06
3      5.778339e+06
4      6.350099e+06
           ...
995    7.199600e+06
996    6.221936e+06
997    6.891513e+06
998    7.058556e+06
999    6.010245e+06
Name: date, Length: 1000, dtype: float64

In [58]:
# in hours

(today - messages['date'])/np.timedelta64(1,'h')

0      104657.326428
1      101394.493094
2      113057.809761
3       96305.643094
4      105834.976428
           ...
995    119993.326428
996    103698.926428
997    114858.543094
998    117642.593094
999    100170.743094
Name: date, Length: 1000, dtype: float64